name: Development Pipeline
on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]

jobs:
  # lint and format
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Display current date
        run: date
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
            GITHUB_TOKEN: ${{ secrets.REPO_TOKEN  }}
            WITH_V: true
            DEFAULT_BUMP: patch
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install
        run: npm install
      - name: Lint
        run: npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: CI/CD apply formatting changes
          branch: ${{ github.head_ref }}
      - name: Run tests
        run: yarn test

  # preview branch in surge.sh
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.REPO_TOKEN }}
          dist: build
          teardown: "true"
          failOnError: "true"
          build: |
            npm install
            npm run build
            
  deploying_to_surge:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install surge and fire deployment
        run: npm install -g surge
      - name: Install all packages
        run: npm install
      - run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
