name: Development Pipeline
on:
  push:
    branches:
      - "main"
jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Display current date
        run: date
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install
        run: npm install
      - name: Lint
        run: npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
